[versions]
agp = "8.13.0"
kotlin = "2.2.21"
kotlinReflect = "2.2.0"
preference = "1.2.1"
appcompat = "1.7.1"
navigation = "2.9.5"
splashScreen = "1.0.1"
material = "1.14.0-alpha06"
aboutLibraries = "13.1.0"

[libraries]
kotlin-reflect = { module = "org.jetbrains.kotlin:kotlin-reflect", version.ref = "kotlinReflect"}
androidx-preference = { group = "androidx.preference", name = "preference", version.ref = "preference" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
androidx-navigation = { group = "androidx.navigation", name = "navigation-fragment", version.ref = "navigation" }
androidx-splashscreen = { group = "androidx.core", name = "core-splashscreen", version.ref = "splashScreen" }
google-material = { group = "com.google.android.material", name = "material", version.ref = "material" }
aboutlibraries-view = { module = "com.mikepenz:aboutlibraries", version.ref = "aboutLibraries" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
aboutLibraries = { id = "com.mikepenz.aboutlibraries.plugin.android", version.ref = "aboutLibraries" }